#:schema https://dystroy.org/bacon/.bacon.schema.json

default_job = "run"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "clippy", "--workspace", "--all-targets", "--", "-D", "warnings"]

[jobs.run]
command = [
  "cargo",
  "run",
]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
